image:
  repository: rancher/rancher-operator
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""

capi:
  enabled: false

rke:
  enabled: false

# tolerations for the webhook deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []
